### ISSUE TITLE
Learn: omit courseruns with a status of "unpublished" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3030] opened 2020-07-07 12:33 UTC
As a search user, I don't want to see courses in search results that I can't (or shouldn't) enroll in. 

#### Acceptance Criteria:

- [ ] don't index courseruns with a status of "unpublished" 
- [ ] don't index courses that only have "unpublished" course runs 

Note: once this is done, it should have the effect of omitting all the [courses in the blocklist](https://github.com/mitodl/open-resource-blocklists/blob/master/courses.txt).

**Comment by mbertrand** [comment] 2020-12-08 16:40
I think this can be closed (dupe of #3211)

**Closed** 2021-05-14 12:06 UTC
