### ISSUE TITLE
Snackbar messages occasionally freeze

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1059] opened 2018-08-13 19:57 UTC
While using the app locally and on deployed environments, I've noticed that snackbar messages can occasionally freeze and remain on the screen until the page is refreshed. I have not been able to reliably reproduce this, so we'll probably need to nail down the steps to reproduce before starting work on this

**Comment by aliceriot** [comment] 2018-08-14 15:18
I think this issue is a dupe of #443

**Closed by aliceriot** 2018-08-14 15:18 UTC
Labels: Blocked, bug
