### ISSUE TITLE
Snackbar message sometimes sticks around

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#443] opened 2018-01-22 15:51 UTC
I'm noticing the snackbar message is sticking around indefinitely:
![screenshot from 2018-01-22 10-46-44](https://user-images.githubusercontent.com/863262/35229506-98f6a850-ff61-11e7-9c3e-e3264064cb1b.png)

To reproduce I reported the same post twice in a row

**Comment by mbertrand** [comment] 2018-10-04 17:44
This might be fixed already?  Reported posts/comments multiple times but was unable to reproduce.  Also tried adding & removing moderators.

**Comment by pdpinch** [comment] 2018-10-09 12:49
I'm closing this. If we find it again, we can re-open.

**Closed by pdpinch** 2018-10-09 12:49 UTC
Labels: bug
