### ISSUE TITLE
Inconsistent cropping of course thumbnails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2211] opened 2019-09-13 12:51 UTC
### Steps to Reproduce

on RC, [search for "functional genomics"](https://discussions-rc.odl.mit.edu/courses/search?q=functional%20genomics)

### Expected Behavior

I think all thumbnails should be the same width. 

If that is complicated with OCW source images, then at least limit the line length of the metadata. 

### Actual Behavior

<img width="892" alt="image" src="https://user-images.githubusercontent.com/430126/64863626-4f963200-d603-11e9-9de2-fdd233fb7b80.png">

**Comment by aliceriot** [comment] 2019-09-23 16:41
I think this was (inadvertently!) fixed by https://github.com/mitodl/open-discussions/pull/2235:

![fixxxjdjdjdjd](https://user-images.githubusercontent.com/6207644/65445111-83413b00-ddff-11e9-964f-4e022357d41f.png)

**Comment by aliceriot** [comment] 2019-09-24 14:05
going to close, we can re-open if the issue is still there but it seems fixed to me

**Closed by aliceriot** 2019-09-24 14:05 UTC
Labels: bug
