### ISSUE TITLE
BUG: Channels sometimes disappear for no reason

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#684] opened 2018-05-08 18:57 UTC
Sometimes when the Discussions home page loads, the channels are not shown. I can recreate this bug by doing the following:

1. Go to micromasters on production and log in, then go to discussions. (You should see the front page with some channels in the left column)
2. click on settings. Then on the settings page, click save.
3. In the header, click on "Micromasters"... (Not Discussions). You should be back at the mm home page.
4. Now click the back button in the browser. You are back at the settings page
5. Now click on "discussions" in the header.

When I do this, I end up back on the discussions home page, but no channels are displayed. If I hit refresh, the channels show up.

**Comment by rhysyngsun** [comment] 2018-05-14 15:48
@roberthouse54 I can't reproduce this in production testing with Firefox and Chrome, are you seeing in in a different browser or is this no longer happening?

**Comment by pdpinch** [comment] 2018-05-16 18:15
@roberthouse54 I can't reproduce this either. If you can, can you take a look at your network or javascript console to see if there any errors?

**Comment by roberthouse54** [comment] 2018-05-16 18:17
OK, I'll take a look.

**Comment by pdpinch** [comment] 2018-05-17 12:13
Rob showed me how to reproduce this. I'll add some screenshots to make it clearer. No obvious API or JavaScript errors.

**Comment by aliceriot** [comment] 2018-05-17 15:10
I think this should happen any time were the initial entry point to the app is the settings page. It's due to the logic for when we fetch the subscribed channels in `App.js`. I can add a quick fix.

**Comment by pdpinch** [comment] 2018-05-18 13:11
Since there's a PR open, I'm moving this to In Progress.

**Closed** 2018-05-18 18:34 UTC
Labels: bug
